export const enum ContractStatus {
  REQUESTED = 'REQUESTED',
  ACTIVE = 'ACTIVE',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  AD_DELETED = 'AD_DELETED',
  DELETED = 'DELETED',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN'
}
